### ISSUE TITLE
Config tepm folder

### ISSUE THREAD

**Issue by ddavlet** [ddavlet/webserv#46]
Temporary folder definition should be part of configuration

**Comment by lodeme** [comment]
Not sure this is important for the configuration because this is not meant to accept any requests made to it, rather this is an internal server thing

**Comment by ddavlet** [comment]
@lodeme I know that it is part of nginx configuration, however I'm not sure that it is mandatory one

**Comment by ddavlet** [comment]
https://github.com/ddavlet/webserv/issues/47
is actually a conflict that may arise
