### ISSUE TITLE
Mime type potential issue

### ISSUE THREAD

**Issue by ddavlet** [ddavlet/webserv#53]
std::string Response::_getMimeType(const std::string& filename) function takes any occurrence. 
File extention is always in the end of file name.

**Comment by lodeme** [comment]
what is the issue generated here? and in which cases?

itested uploading .jpeg files even if it's not defined in the mime types and it worked well

**Comment by lodeme** [comment]
<img width="2560" alt="Screenshot 2024-08-08 at 15 21 54" src="https://github.com/user-attachments/assets/4d6f06d6-a131-47ed-9e6c-bc7a9fb285cf">

okay so testing to download a jpeg we can see it only loads a chunk of it, and then starts loading forever on the server without completing.

**Comment by ddavlet** [comment]
this was not because of mimetype. Overall issue still persists, however it is not critical
